language: python
python:
  - "3.6"

# command to install dependencies
before_install:
  - cd YummyRecipesApi/

install:
  - pip install -r requirements.txt

# command to run tests
script: python manage.py test api