# Generated by Django 2.1 on 2018-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180809_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
